### PR TITLE
feat: added save and restore highscore between instances of game

### PR DESCRIPTION
**Pull request by sourabhaa**
@chimosky @quozl @srevinsaju kindly review the PR.

### CODE REVIEW

**Comment by quozl** [comment]
I'm curious, why not use the activity write_file method and the journal instead of a file?

**Comment by sourabhaa** [comment]
> I'm curious, why not use the activity write_file method and the journal instead of a file?

The read_file and and write_file methods are used to save and restore data from the journal when the game is resumed. This does not store the data between instances.

**Comment by quozl** [comment]
Thanks.  Previous to this patch the high score was saved in the journal object, and during resume was loaded and passed to the game via the restore_game method.  Your changes are to the constructor, but the activity will still call restore_game.  I don't understand how this works; it would seem that it could not, and the high school from the journal object will override what is read from the new file.  Can you confirm you have tested inside Sugar using the activity, and not by running the math_hurdler.py file directly?

**Comment by sourabhaa** [comment]
Yes @quozl, I've tested inside Sugar. So when new instance is started, `load_highscore` is called, `restore_game` will not be called here so it does not override the high score value. The `write_file` is called when the game page is closed where the high score is store to the journal object. When the game is resumed, `restore_game` is called which will override what is read from the new file, but I'm passing the same value high score in both `save_highscore` and `write_file` when the game is stopped, so the user can choose to start a new game or resume current game, the high score value remains the same.

**Comment by quozl** [comment]
Oh, okay.  Seems a bit redundant, but never mind/

**Comment by sourabhaa** [comment]
@chimosky, kindly review :)

**Comment by chimosky** [comment]
Currently at master the highscore is saved across instances, resuming or starting an activity instance has the same highscore.

Did you check to confirm?

**Comment by sourabhaa** [comment]
@chimosky I've checked, it doesn't store the high score across instances. It stores only when resumed.

**Comment by chimosky** [comment]
It seems I was testing another activity earlier and confused that for this one, tested this now and the game freezes when an answer is wrong and the logs show this;
```
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/math_hurdler.py", line 393, in run
    self.save_highscore()
  File "/home/ibiam/Activities/math-hurdler/math_hurdler.py", line 146, in save_highscore
    if int_highscore < self.points:
UnboundLocalError: local variable 'int_highscore' referenced before assignment
```

Seems pygame events aren't handled properly as this is also seen in the logs;
```
1665405581.977438 ERROR root: Event queue full!
1665405581.983363 ERROR root: Event queue full!
1665405581.991884 ERROR root: Event queue full!
1665405581.998326 ERROR root: Event queue full!
1665405582.006991 ERROR root: Event queue full!
1665405582.021957 ERROR root: Event queue full!
1665405582.467504 ERROR root: Error saving activity object to datastore
Traceback (most recent call last):
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 1277, in _prepare_close
    self.save()
  File "/usr/lib/python3.7/dist-packages/sugar3/activity/activity.py", line 978, in save
    self.write_file(file_path)
  File "/home/ibiam/Activities/math-hurdler/math_hurdlerActivity.py", line 95, in write_file
    score, hscore, play_state, hurdle_number = self.game.write_file()
  File "/home/ibiam/Activities/math-hurdler/math_hurdler.py", line 124, in write_file
    self.save_highscore()
  File "/home/ibiam/Activities/math-hurdler/math_hurdler.py", line 146, in save_highscore
    if int_highscore < self.points:
UnboundLocalError: local variable 'int_highscore' referenced before assignment
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 112, in _quit_cb
    pygame.event.post(pygame.event.Event(pygame.QUIT))
pygame.error: Event queue full
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 109, in _screen_changed_cb
    self.update_display()
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full
```

The last part of the debug error has to do with this PR, could you also fix the event handling? Thanks!

**Comment by sourabhaa** [comment]
@chimosky , I've fixed the issue. The event handling issue was due to freezing of game. It's working fine now.

**Comment by chimosky** [comment]
Tested, works as expected. Thanks!

**Pull request merged**
