### PR TITLE
Fixed activity freezing on Gameover

### PR DESCRIPTION
**Pull request by SudoSu-bham**
It was hard coded to pause the activity for 6000 milliseconds

### CODE REVIEW

**Comment by chimosky** [comment]
Haven't tested your change yet, but why do you still check if the time is >= 6000 ms?

**Comment by SudoSu-bham** [comment]
> Haven't tested your change yet, but why do you still check if the time is >= 6000 ms?

So that gameover screen stays for `6000ms`. I did this because this was the default time set in the activity. If we don't check for `time >= 6000ms` than gameover screen will close immediately. 

I just fixed the freezing of the activity without making any changes to the overall game play.

**Comment by chimosky** [comment]
Tested master and tested your change, there's no difference.

The game over screen doesn't freeze on master, a sound plays while it shows, same thing happens on your branch.

**Comment by SudoSu-bham** [comment]
But I was unable to click on `Stop button` when game over screen is visible in master. Are you able to click on `Stop button` during game over?

**Comment by chimosky** [comment]
> But I was unable to click on `Stop button` when game over screen is visible in master. Are you able to click on `Stop button` during game over?

Tested and I can reproduce, merged by hand. Thank you!

Edited your commit message as it wasn't clear why your change was being made.

**Pull request closed without merging**
