### PR TITLE
Replace activity icon

### PR DESCRIPTION
**Pull request by vaibhav-sangwan**
* activity-generic.svg does not represent MathHurdler Activity correctly

@chimosky @quozl please review

### CODE REVIEW

**Comment by vaibhav-sangwan** [comment]
Removed the mention of "MathHurdler" from commit message

**Comment by walterbender** [comment]
The svg contains inkscape messages. Please save as "plain svg" from inkscape.

**Comment by vaibhav-sangwan** [comment]
Exporting as plain SVG still adds inkscape messages to the file. Removed the messages manually after replacing.

**Comment by walterbender** [comment]
Hmm. I've never seen Inkscape include its state messages in plain SVG output.

**Pull request merged**
