### PR TITLE
fix: fixed save and restore game state

### PR DESCRIPTION
**Pull request by sourabhaa**
Fixed the Save and restore game state feature. It was broken when https://github.com/sugarlabs/math-hurdler/commit/5eeab2e750eb95bdefee09a9137e100e62b3c01d was added. Also fixed the hurdler number not getting updated after restoring the game state. @chimosky kindly review the MR.

### CODE REVIEW

**Comment by quozl** [comment]
Please add your explanation to the commit messages. See [commit messages](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits).

**Comment by sourabhaa** [comment]
@quozl , I've updated the commit message. Kindly review.

**Comment by quozl** [comment]
Thanks, looks good.

**Comment by chimosky** [comment]
Reviewed, thanks!

**Pull request merged**
