### PR TITLE
Add textures to ground and grass.

### PR DESCRIPTION
**Pull request by sparshg**
@chimosky Added some textures I made.

### CODE REVIEW

**Comment by chimosky** [comment]
Tested 7476c8a, activity failed to start and this was in the logs;

```
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/math_hurdler.py", line 147, in run
    ground = pygame.transform.scale(ground, (screen_size[0], screen_size[1] / 3))
TypeError: integer argument expected, got float
1661339520.605166 ERROR root: Event queue full!
1661339520.611587 ERROR root: Event queue full!
1661339520.619982 ERROR root: Event queue full!
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 112, in _quit_cb
    pygame.event.post(pygame.event.Event(pygame.QUIT))
pygame.error: Event queue full
Traceback (most recent call last):
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 109, in _screen_changed_cb
    self.update_display()
  File "/home/ibiam/Activities/math-hurdler/sugargame/event.py", line 98, in update_display
    pygame.event.post(pygame.event.Event(pygame.VIDEOEXPOSE))
pygame.error: Event queue full
```

**Comment by sparshg** [comment]
Fixed, had to cast scale arguments to int

**Comment by chimosky** [comment]
Could you edit the commit message in 5696f01 as it doesn't tell what was done in the commit, the change wasn't to make the activity compatible with pygame 1.9.4 as it was already compatible with that.

**Comment by sparshg** [comment]
Changed commit message.

**Comment by chimosky** [comment]
Tested, works as expected. Thanks!

**Pull request merged**
